SELECT * FROM EMPLOYEES;

-- get me how many different departments we have for each location_id
SELECT * FROM DEPARTMENTS;
SELECT COUNT (*) FROM DEPARTMENTS;
SELECT COUNT (LOCATION_ID) FROM DEPARTMENTS;

SELECT DISTINCT LOCATION_ID FROM DEPARTMENTS;
SELECT Count (DISTINCT LOCATION_ID) FROM DEPARTMENTS;

SELECT LOCATION_ID, Count (*) as "TOTAL COUNT FOR EACH LI" FROM DEPARTMENTS
GROUP BY LOCATION_ID;

-- get me how many locations we have for each country
SELECT COUNTRY_ID, COUNT(*) FROM LOCATIONS
GROUP BY COUNTRY_ID
ORDER BY COUNTRY_ID; -- or we say ORDER BY 1

SELECT * FROM LOCATIONS;


-- get me how many countries we have for each region
SELECT REGION_ID, COUNT(*) FROM COUNTRIES
GROUP BY REGION_ID
ORDER BY REGION_ID DESC;

